ingress:
    enabled: true
    path: /
    hosts:
        - grafana.k3s.zhome.local

adminPassword: admin
image:
    tag: 9.5.2

persistence:
    enabled: true
    storageClassName: longhorn
    size: 10Gi

datasources:
    datasources.yaml:
        apiVersion: 1
        datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus.k3s.zhome.local
              isDefault: true

dashboardProviders:
    dashboardproviders.yaml:
        apiVersion: 1
        providers:
            - name: "default"
              orgId: 1
              folder: ""
              type: file
              disableDeletion: false
              editable: true
              options:
                  path: /var/lib/grafana/dashboards/default

dashboards:
    default:
        prometheus-stats:
            gnetId: 2
            revision: 2
            datasource: Prometheus
        node-exporter:
            gnetId: 1860
            revision: 31
            datasource: Prometheus
        traefik:
            gnetId: 4475
            revision: 5
            datasource: Prometheus
        pop-metrics:
            gnetId: 747
            revision: 2
            datasource: Prometheus
        k3s:
            gnetId: 12869
            revision: 3
            datasource: Prometheus
        kubernetes-cluster-monitoring:
            gnetId: 315
            revision: 3
            datasource: Prometheus
